### ISSUE TITLE
Provide extension points for customized scripts

### ISSUE THREAD

**Issue by caroline-church** [sstone1/blockchain-starter-kit#16]
Add extension points to the main scripts to allow developers to add in their own deployment scripts

**Comment by jt-nti** [comment]
Someone using a toolchain created using the starter kit template may want to make changes to handle aspects of their solution that are not part of the starter kit. For example, pre-loading data onto the blockchain, sending pager duty alerts, building apps in C/other languages, deploying integrations other than REST, etc.

Some of these may be best approached by simply adding to or modifying the starter kit build scripts. Others are likely to be more suited to additional build stages or toolchain integrations.

This issue is likely to be addressed through a combination of script documentation in #18 taking account of any approaches for delivering script updates in #17, and links to the toolchain docs and tutorials.

**Comment by jt-nti** [comment]
Now covered in IBM-Blockchain-Starter-Kit/build-lib#6
